FROM node:22.16.0-alpine3.22
WORKDIR /app

ARG NPM_TOKEN


# Enable pnpm
RUN corepack enable

# Install all dependencies
COPY package.json pnpm-lock.yaml ./
COPY .npmrc .npmrc
RUN printf "\n//npm.pkg.github.com/:_authToken=${NPM_TOKEN}\n" >> .npmrc
RUN pnpm install --frozen-lockfile

COPY . .

# Run in the dev mode with hot reload
CMD ["node", "ace", "serve", "--watch"]